development:
  db_name: template_development
  db_user: template
  db_pass: template

  app_name: template

  domain: localhost:3000

  noreply_email: noreply@template.app

staging:
  db_name: template_staging
  db_user: template
  db_pass: template

  app_name: template

  domain: staging.template.app

  noreply_email: noreply@template.app

production:
  db_name: template_production
  db_user: template
  db_pass: template

  app_name: template

  domain: template.app

  noreply_email: noreply@template.app

test:
  db_name: template_test
  db_user: template
  db_pass: template

  app_name: template

  domain: localhost:3000

  noreply_email: noreply@template.app


